export interface Device {
    did: string,
    token: string,
    longitude: string,
    latitude: string,
    name: string,
    pid: string,
    localip: string,
    mac: string,
    ssid: string,
    bssid: string,
    parent_id: string,
    parent_model: string,
    show_mode: number,
    model: string,
    adminFlag: number,
    shareFlag: number,
    permitLevel: number,
    isOnline: boolean,
    desc: string,
    desc_new: string,
    desc_time: number[],
    extra: Record<string, unknown>,
    event: Record<string, string>,
    uid: number,
    pd_id: number,
    password: string,
    p2p_id: string,
    rssi: number,
    family_id: number,
    reset_flag: number
}
